language: python
python:
  - "2.7"
  - "pypy"
before_install:
  - pip install --upgrade flake8 pytest coveralls
  - flake8 .
install:
  - pip install .
sudo: false
script: python setup.py test
after_success: coveralls
